<?php
/*
Template Name: What's New What's Fresh What's Happening Plugin Page
*/
?>
<?php get_header(); ?>

	<div id="content" class="narrowcolumn">

		<?php if (have_posts()) : while (have_posts()) : the_post(); ?>
		<div class="post" id="post-<?php the_ID(); ?>">
		<h2><?php the_title(); ?></h2>
			<div class="entry">
				<?php the_content('<p class="serif">Read the rest of this page &raquo;</p>'); ?>

				<?php wp_link_pages(array('before' => '<p><strong>Pages:</strong> ', 'after' => '</p>', 'next_or_number' => 'number')); ?>

			</div>
		</div>
		<?php endwhile; endif; ?>
	<?php edit_post_link('Edit this entry.', '<p>', '</p>'); ?>

	<?php whats_new_whats_fresh_whats_happening(); ?>

	<p style="font-size:0.8em;">This page is generated by the <a href="http://www.bochgoch.com/page/plugin/wp_wnwfwh/">What's New What's Fresh What's Happening Plugin</a> from bochgoch.com</p>

	</div>

<?php get_sidebar(); ?>

<?php get_footer(); ?>